steps:
  - name: 'python:3.11'
    dir: 'Backend'  
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']
    id: 'install-deps'

  # Deploy to Compute Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Copy Backend directory to server
        gcloud compute scp --recurse --zone=us-central1-a Backend/ web-server:/tmp/app/
        
        # Deploy on the server
        gcloud compute ssh web-server --zone=us-central1-a --command="
          # Stop existing application
          sudo pkill -f gunicorn || true
          sudo pkill -f python || true
          
          # Move new code
          sudo rm -rf /var/www/app || true
          sudo mv /tmp/app /var/www/app
          sudo chown -R www-data:www-data /var/www/app
          
          # Install dependencies and setup
          cd /var/www/app
          sudo pip3 install -r requirements.txt
          
          # Set environment variables for production
          export GOOGLE_CLOUD_PROJECT=final-project-472521
          export DJANGO_SETTINGS_MODULE=api.settings
          
          # Run Django commands
          sudo -E python3 manage.py collectstatic --noinput || true
          sudo -E python3 manage.py migrate || true
          
          # Start the application with correct wsgi path
          cd /var/www/app
          sudo -E python3 -m gunicorn --bind 0.0.0.0:8000 --daemon api.wsgi:application
        "
    id: 'deploy'
    waitFor: ['install-deps']

timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY